import type { Command } from '../../../types';

// Compact emoji dataset: [emoji, keywords...]. Keywords in DE + EN for good matching.
const EMOJI: ReadonlyArray<readonly [string, string]> = [
  ['😀', 'grinsen smile happy lachen face'],
  ['😂', 'lachen tränen laughing joy lol'],
  ['🤣', 'rofl lachen rolling boden'],
  ['😊', 'lächeln smile blush freundlich'],
  ['😍', 'verliebt love herzen heart eyes'],
  ['😘', 'kuss kiss küssen'],
  ['😎', 'cool sonnenbrille sunglasses'],
  ['🤔', 'denken thinking nachdenken hmm'],
  ['😉', 'zwinkern wink'],
  ['😢', 'traurig sad weinen cry'],
  ['😭', 'weinen crying sad heulen'],
  ['😡', 'wütend angry sauer'],
  ['😱', 'schock scream angst shock'],
  ['🥳', 'party feier celebrate'],
  ['🤗', 'umarmung hug'],
  ['😴', 'schlafen sleep müde tired'],
  ['🙄', 'augenrollen eyeroll genervt'],
  ['😅', 'schwitzen sweat nervös'],
  ['🤩', 'sterne star augen wow'],
  ['🥺', 'bettelaugen pleading süß'],
  ['👍', 'daumen hoch thumbs up gut like ok'],
  ['👎', 'daumen runter thumbs down schlecht'],
  ['👏', 'klatschen clap applaus'],
  ['🙏', 'beten danke pray please thanks'],
  ['🙌', 'hände hoch raised celebrate'],
  ['💪', 'muskel strong stark power'],
  ['🤝', 'handschlag deal handshake'],
  ['✌️', 'peace victory sieg'],
  ['👋', 'winken wave hallo bye'],
  ['🤞', 'daumen drücken fingers crossed glück'],
  ['🫶', 'herz hände love'],
  ['❤️', 'herz heart love rot liebe'],
  ['🧡', 'herz orange'],
  ['💛', 'herz gelb yellow'],
  ['💚', 'herz grün green'],
  ['💙', 'herz blau blue'],
  ['💜', 'herz lila purple'],
  ['🖤', 'herz schwarz black'],
  ['💔', 'herz gebrochen broken'],
  ['💯', 'hundert 100 perfekt perfect'],
  ['🔥', 'feuer fire lit hot heiß'],
  ['✨', 'glitzer sparkle funkeln'],
  ['⭐', 'stern star favorit'],
  ['🌟', 'stern glanz star'],
  ['⚡', 'blitz lightning strom power'],
  ['💥', 'explosion boom knall'],
  ['🎉', 'party konfetti celebrate tada'],
  ['🎊', 'konfetti party'],
  ['🎈', 'luftballon balloon'],
  ['🎁', 'geschenk gift present'],
  ['🏆', 'pokal trophy gewinner sieg'],
  ['🥇', 'gold erster medaille first'],
  ['✅', 'check haken ok richtig done erledigt'],
  ['❌', 'kreuz falsch wrong nein no x'],
  ['⚠️', 'warnung warning achtung'],
  ['❓', 'fragezeichen question frage'],
  ['❗', 'ausrufezeichen wichtig important'],
  ['💡', 'idee idea glühbirne licht'],
  ['📌', 'pin pinnen anheften'],
  ['📎', 'büroklammer clip anhang'],
  ['🔒', 'schloss lock sicher gesperrt'],
  ['🔑', 'schlüssel key passwort'],
  ['💰', 'geld money sack reich'],
  ['💸', 'geld fliegt money ausgeben'],
  ['💳', 'kreditkarte card zahlen'],
  ['🛒', 'einkaufswagen cart shopping'],
  ['🕐', 'uhr clock zeit time'],
  ['⏰', 'wecker alarm uhr'],
  ['📅', 'kalender calendar datum'],
  ['📞', 'telefon phone anruf'],
  ['📱', 'handy smartphone phone mobil'],
  ['💻', 'laptop computer pc'],
  ['🖥️', 'computer desktop pc monitor'],
  ['⌨️', 'tastatur keyboard'],
  ['🖱️', 'maus mouse'],
  ['🎮', 'gaming controller spiel game'],
  ['🎧', 'kopfhörer headphones musik'],
  ['📷', 'kamera camera foto'],
  ['🔋', 'batterie battery akku'],
  ['🔌', 'stecker plug strom'],
  ['💾', 'speichern save diskette'],
  ['📁', 'ordner folder datei'],
  ['📂', 'ordner offen folder open'],
  ['🗑️', 'mülleimer trash löschen delete'],
  ['🔍', 'lupe search suche zoom'],
  ['⚙️', 'zahnrad settings einstellungen gear'],
  ['🔧', 'schraubenschlüssel tool werkzeug fix'],
  ['🚀', 'rakete rocket launch start schnell'],
  ['🐛', 'käfer bug fehler error'],
  ['☕', 'kaffee coffee tasse'],
  ['🍕', 'pizza essen food'],
  ['🍔', 'burger essen food'],
  ['🍻', 'bier beer prost cheers'],
  ['🎵', 'note musik music'],
  ['🎶', 'noten musik music'],
  ['🌈', 'regenbogen rainbow'],
  ['☀️', 'sonne sun sonnig'],
  ['🌙', 'mond moon nacht'],
  ['⛅', 'wolke wetter cloud'],
  ['🌧️', 'regen rain wetter'],
  ['❄️', 'schnee snow kalt schneeflocke'],
  ['🐱', 'katze cat'],
  ['🐶', 'hund dog'],
  ['🦄', 'einhorn unicorn'],
  ['👀', 'augen eyes schauen look'],
  ['🧠', 'gehirn brain denken'],
  ['🤖', 'roboter robot bot ki ai'],
  ['👻', 'geist ghost halloween'],
  ['💩', 'kacke poop'],
  ['🎯', 'ziel target dart treffer'],
  ['📈', 'chart hoch steigen wachstum graph'],
  ['📉', 'chart runter fallen graph'],
  ['📊', 'balken chart statistik diagramm'],
];

const emojiCommands: readonly Command[] = [
  {
    id: 'emoji',
    trigger: '/emoji ',
    description: 'Emoji suchen & kopieren',
    usage: 'z.B. /emoji feuer  •  /emoji herz  •  /emoji rocket',
    aliases: ['/e '],
    category: 'text',
    handler(args: string) {
      const q = args.trim().toLowerCase();
      if (!q) {
        return { results: [{ id: 'cmd-usage', title: 'Emoji suchen', subtitle: '/emoji feuer · /emoji herz · /emoji rocket', type: 'calc' }] };
      }
      const matches = EMOJI.filter(([, kw]) => kw.includes(q)).slice(0, 12);
      if (matches.length === 0) {
        return { results: [{ id: 'cmd-err', title: 'Kein Emoji gefunden', subtitle: `Nichts für "${q}"`, type: 'system' }] };
      }
      return {
        results: matches.map(([emoji, kw], i) => ({
          id: `emoji-${i}`,
          title: `${emoji}  ${kw.split(' ')[0]}`,
          subtitle: 'Enter zum Kopieren',
          type: 'calc' as const,
          path: emoji,
          copyToClipboard: emoji,
        })),
      };
    },
    enabled: true,
  },
];

export default emojiCommands;
